### ISSUE TITLE
address selection

### ISSUE THREAD

**Issue by marsxul** [amigocloud/modified-tripplanner#100]
I can no longer select the from or to bars and click in the map to have it select the clicked address or location.

**Comment by lukewhyte** [comment]
I believe I was fixing some geocode bugs when this issue was found, which is likely why it appeared to be broken. It is working fine on my machine. Can someone else confirm that it is working on theirs?

**Comment by marsxul** [comment]
this works from a fresh new cache cleared browser version.  but once you have planned a trip, you cannot clear the address and then re-select the address by clicking on the screen.
