### ISSUE TITLE
GTFS feed not working from a variety of Bay area agencies

### ISSUE THREAD

**Issue by marsxul** [amigocloud/modified-tripplanner#101]
santa cruz metro transit is not coming up in the trip options.

**Comment by vchernetsky** [comment]
GTFS Feeds they have are not updated in the long time. I cannot find current GTFS feed for those agencies.

21:50:40.425 WARN (Graph.java:541) Agency Santa Cruz Metro has no calendar dates which are after today; no trips will be plannable on this agency
21:50:40.426 WARN (Graph.java:541) Agency AC Transit has no calendar dates which are after today; no trips will be plannable on this agency
21:50:40.426 WARN (Graph.java:541) Agency SFMTA has no calendar dates which are after today; no trips will be plannable on this agency

**Comment by marsxul** [comment]
seems like GTFS exchange is shutting down.
Transitfeeds and transitland is picking up the slack
http://transitfeeds.com/l/67-california-usa  - This has santa cruz metro, sfmta, actransit

this site looks nice as it breaks it down into static schedule and real time updates and vehicles.  

https://transit.land/feed-registry/  has ac transit, sfmta but not santa cruz metro

**Comment by vchernetsky** [comment]
I'll revise the GTFS sources.

Caltrain has invalid GTFS file, it has subfolder in it. I guess I have to write a script to repackage it into a valid GTFS file.

BTW, Transitfeeds.com has the same invalid Caltrain GTFS :)

**Comment by marsxul** [comment]
hmmmmm, that's weird.  I just checked and both feeds are the same txt files.  transitland seems easier, is that what you are going with.  

looks like both are inside 2016APR_GTFS folder. 

not sure if we need to subscribe to developer changes http://www.caltrain.com/developer/developer-notifications.html

**Comment by 3vivekb** [comment]
A link to the invalid Santa Cruz feed:
http://transitfeeds.com/p/santa-cruz-metro/343
