### ISSUE TITLE
Web in mobile on Android phone can't select Google Addresses

### ISSUE THREAD

**Issue by 3vivekb** [amigocloud/modified-tripplanner#105]
How to Recreate:
When accessing vta2.amigocloud.com from an Android phone running 6.0.1
Start typing in an address. An autocomplete pops up - click on a suggested address.

Expected Result:
The selected address populates into the Origin field.

Actual Result:
Selecting the address links to Google Maps or Google Earth.

![screenshot_20160706-092517](https://cloud.githubusercontent.com/assets/4524205/16626089/3b606a90-435c-11e6-9798-8f5dcebdcc13.png)
![screenshot_20160706-092523](https://cloud.githubusercontent.com/assets/4524205/16626088/3b5f510a-435c-11e6-97d5-954505200686.png)

**Comment by vchernetsky** [comment]
The address entering is a painful experience. 
- Keyboard covering the text field.
- Selection of the address from drop down list won't remove drop down list
- Tapping on the list item sometimes jumps to Google Maps app.

**Comment by 3vivekb** [comment]
PRIORITY BUG

**Comment by 3vivekb** [comment]
Tested.  It's fixed!

**Comment by 3vivekb** [comment]
e2fe06168518aa704b3eed72913bbdbbc01391b9
