### ISSUE TITLE
the final stage of the help function in the hamburger menu

### ISSUE THREAD

**Issue by marsxul** [amigocloud/modified-tripplanner#119]
the final stage of the help function from the hamburger doesn't allow you to move on to the next stage.  it stops at help me choose. 

![image](https://cloud.githubusercontent.com/assets/7337996/17003058/1c79c8b0-4e83-11e6-83ee-900caa014135.png)

**Comment by 3vivekb** [comment]
This also crashes the app - you can't get out.
