### ISSUE TITLE
When Car mode is disabled the OTP query still has a car as an option.

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#12]
Same for biking.

There should be no CAR in directModes= option

http://vta2.amigocloud.com/api/otp/profile?accessModes=WALK%2CBICYCLE%2CBICYCLE&bikeSafe=1000&bikeSpeed=4.1&date=2015-05-05&directModes=CAR%2CWALK%2CBICYCLE%2CBICYCLE&egressModes=WALK%2CBICYCLE&endTime=19%3A00&from=37.3189582824707%2C-122.02928161621094&startTime=15%3A00&to=37.78718322515488%2C-122.40025475621223&limit=2&transitModes=BUS%2CTRAINISH&walkSpeed=1.4&maxWalkTime=60&minCarTime=1&maxCarTime=20&maxBikeTime=60

**Comment by wocoburguesa** [comment]
Now happening with bike. Check other types.

**Comment by rburhum** [comment]
These would be nice pull requests for the main branch of modeify. Please make sure we can do pull requests to contribute those changes back.
