### ISSUE TITLE
Auto-complete Map search is only searching for "Places"

### ISSUE THREAD

**Issue by 3vivekb** [amigocloud/modified-tripplanner#125]
When you search in the box for an address, it only picks up addresses that are registered to places.

For example, if you search Quiznos, A quiznos address will show up.

If you search your home address, it won't show up.

Expected Behaviour:
Addresses of homes plus places show up in the search bar.

Actual Behaviour
Only Addresses assigned to a place show up.

**Comment by vchernetsky** [comment]
The issue is the Google API KEY. I returned our AmigoCloud key and it works again.
