### ISSUE TITLE
Route calculated, but not displayed

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#24]
http://vta2.amigocloud.com/planner?from=485%20Lucas%20Ave%2C%20Richmond%2C%20California&to=CA%20242%2C%20Concord%2C%20California&modes=BICYCLE%2CBUS%2CTRAINISH%2CWALK&start_time=8&end_time=15&days=M%E2%80%94F

![uploads/84d18e66-79b5-4510-9437-1d87918b21f6/Screen Shot 2015-05-23 at 11.27.42 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F84d18e66-79b5-4510-9437-1d87918b21f6%2FScreen+Shot+2015-05-23+at+11.27.42+AM.png)

**Comment by wocoburguesa** [comment]
Will work as part of the switch to transitive.js + /plan. Closing it.
