### ISSUE TITLE
After enabling real time popup, routing start/stop icons are not clickable 

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#26]
... and if then clicked yellow "route" button, start/stop isons disappear (in left top corner of the window)

**Comment by wocoburguesa** [comment]
This should no longer be a problem now that we are not using transitive.js anymore.

**Comment by wocoburguesa** [comment]
It may become a problem again once we go back to Nominatim. Suggestion would be to implement realtime into transitive.js, but that sounds insane...

**Comment by wocoburguesa** [comment]
Making progress with transitive.js...
