### ISSUE TITLE
Select popup don't show all the info.

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#55]
Upon choosing select the trip much of the information is missing regarding the travel savings.

**Comment by wocoburguesa** [comment]
Need to tweak some of the params to always have car ride data, so the comparison table can be filled. Removed the select button for now.

**Comment by vchernetsky** [comment]
I don't think we can do that. If we enable car, otp returns only one route and it'll use car in it. Chances are there will be no transit route options.
