### ISSUE TITLE
Change colors to match VTA color schema

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#58]
Example:

![uploads/6a749a85-1a4f-48e3-b995-98f3451103bb/Screen Shot 2015-07-21 at 9.57.03 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6a749a85-1a4f-48e3-b995-98f3451103bb%2FScreen+Shot+2015-07-21+at+9.57.03+AM.png)

Spec:
![uploads/effef140-ab72-4a3f-b32d-3c5ec931f87b/Screen Shot 2015-07-20 at 1.05.18 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feffef140-ab72-4a3f-b32d-3c5ec931f87b%2FScreen+Shot+2015-07-20+at+1.05.18+PM.png)

**Comment by vchernetsky** [comment]
Also change colors of real time icons and popup to match this color schema.

**Comment by vchernetsky** [comment]
Icon for Park & Ride instead of Car. Color of the icon need to change to match color schema. 

![uploads/fa5b9643-d15b-4aa9-b310-1ae3a6c886f6/unnamed.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa5b9643-d15b-4aa9-b310-1ae3a6c886f6%2Funnamed.jpg)

**Comment by vchernetsky** [comment]
Another proposed icon for Park&Ride
![uploads/baa38189-d9e9-45a5-a56a-c609efd78d33/parkandride_icon.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbaa38189-d9e9-45a5-a56a-c609efd78d33%2Fparkandride_icon.jpg)

**Comment by wocoburguesa** [comment]
Let's use the last one. Should take 2 hours. Remember to change the color of the icon.
