### ISSUE TITLE
Check if arrival time is listed in /plan response

### ISSUE THREAD

**Issue by wocoburguesa** [amigocloud/modified-tripplanner#59]

**Comment by vchernetsky** [comment]
There are REST APIs to the OTP back end that provides this info:
http://dev.opentripplanner.org/apidoc/0.15.0/resource_IndexAPI.html

Example:
List of all the stops:
http://vta2.amigocloud.com/api/otp/index/stops

Info about particular stop:
http://vta2.amigocloud.com/api/otp/index/stops/VTA:1109

Times for particular stop:
http://vta2.amigocloud.com/api/otp/index/stops/VTA:1109/stoptimes

The UI/UX for realtime vehicle info is in #62
