### ISSUE TITLE
popups

### ISSUE THREAD

**Issue by marsxul** [amigocloud/modified-tripplanner#92]
Match the stop info popup to the mockup.  However eliminate the (1234) number to the right of the stop name.  Please be sure to add the RTIID below the stop name as in the example. 

Adjust the bus pop up to reflect the UI design, route numner, route name, direction, arrival at next stop.

**Comment by marsxul** [comment]
Bus popups - this is the transitime popup, the information from the transitime feed we need specifically is the following:
Vehicle number
Route
Headsign
Block
Next Stop

![image](https://cloud.githubusercontent.com/assets/7337996/15554756/7ec1a61c-227a-11e6-9eae-52e5c4706b16.png)

**Comment by marsxul** [comment]
Applicable changes for screen space optimization and customer information sharing   The second removal of something I requested, being the block id. 

![image](https://cloud.githubusercontent.com/assets/7337996/16235681/99b9bdea-378a-11e6-9a86-87deb22284b6.png)

Remove the Route in the pop up since it is in the popup header.  Also to simplify it is best we take the block out.  The block info is great for the customer service, but not for our customers.  
Is it possible to include the predicted time of arrival at the next stop location e.g. El Camino & Sylvan 10:43 am?  

![image](https://cloud.githubusercontent.com/assets/7337996/16235693/9f7bf9a0-378a-11e6-97a8-101fab80b4a8.png)

This Iooks awesome, simple and clean.

![image](https://cloud.githubusercontent.com/assets/7337996/16235702/a6e9544e-378a-11e6-8c9f-1c0ff05b7b25.png)

```
Similar to the bus pop up; remove the route, and block information.  The route is in the header.  The Vehicle information is great, but is it possible to get the actual vehicle number, this number is what transitime uses from the Transloc OpenApi.  Transloc collects VTA data then I believe they combine all the data into a master database with all their other clients and the very long vehicle id is created.  Light rail vehicles are 3 digit numbers with an A or B after it representing different sides of the train.  
```

**Comment by lukewhyte** [comment]
I've removed block and route information. Prediction time for next stop arrival is not immediately available. We'd have to make some more API calls to get that information. Should I proceed with that?
