### ISSUE TITLE
after calculating route map doesn't zoom close enough

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#98]
Should zoom closer
![uploads/b12bc16c-4eec-4ad9-98ae-82fa284472d8/Screen Shot 2016-06-03 at 2.46.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb12bc16c-4eec-4ad9-98ae-82fa284472d8%2FScreen+Shot+2016-06-03+at+2.46.47+PM.png)

**Comment by lukewhyte** [comment]
Zoom is now set to match the boundaries of all the route polygons

**Comment by marsxul** [comment]
works great.
